"use client";
import { useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { AppNav } from "@/components/AppNav";
import { getOpportunity, setOpportunityStatus } from "@/lib/mock-data";

export default function OpportunityDetailPage() {
  const params = useParams<{ id: string }>(); const [message, setMessage] = useState(""); const opp = getOpportunity(params?.id);
  if (!opp) return <main className="min-h-screen"><AppNav /><div className="mx-auto max-w-3xl px-5 py-12">Not found. <Link href="/dashboard" className="font-semibold text-indigo-600">Back to Radar</Link></div></main>;
  const deadline = opp.deadline ? new Intl.DateTimeFormat("en", { month: "long", day: "numeric", year: "numeric" }).format(new Date(`${opp.deadline}T00:00:00`)) : "No deadline listed";
  const updateStatus = (status: string) => { setOpportunityStatus(opp.id, status); setMessage(status === "applied" ? "Marked as applied." : "Saved to your list."); };
  return <main className="min-h-screen"><AppNav /><div className="mx-auto max-w-4xl px-5 py-9 sm:px-6"><Link href="/dashboard" className="text-sm font-semibold text-indigo-600">← Back to your Radar</Link><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_280px]"><article className="surface p-6 sm:p-8"><p className="eyebrow capitalize">{opp.category}</p><h1 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">{opp.title}</h1><p className="mt-3 text-lg text-slate-500">{opp.organization}</p><div className="mt-7 grid gap-3 border-y border-slate-100 py-5 text-sm sm:grid-cols-2"><p><span className="block text-xs font-bold uppercase tracking-wider text-slate-400">Location</span><span className="mt-1 block font-medium">{opp.remote ? "Remote" : opp.location}</span></p><p><span className="block text-xs font-bold uppercase tracking-wider text-slate-400">Deadline</span><span className="mt-1 block font-medium">{deadline}</span></p></div><section className="mt-7"><h2 className="text-lg font-bold">Why it matches you</h2><ul className="mt-3 space-y-2">{opp.matchReasons.map((reason, index) => <li key={index} className="flex gap-3 text-sm leading-6 text-slate-600"><span className="font-bold text-indigo-500">+</span>{reason}</li>)}</ul></section><section className="mt-7"><h2 className="text-lg font-bold">About this opportunity</h2><p className="mt-3 leading-7 text-slate-600">A curated opportunity for ambitious builders looking to grow their skills, network, and impact. Visit the official listing for full eligibility and application details.</p></section></article><aside className="surface h-fit p-5"><h2 className="font-bold">Ready to take action?</h2><p className="mt-2 text-sm leading-6 text-slate-500">Save this for later or mark it once you have applied.</p><a href={opp.url} target="_blank" rel="noreferrer" className="button-primary mt-5 w-full">Visit opportunity site ↗</a><button onClick={() => updateStatus("saved")} className="button-secondary mt-2 w-full">Save opportunity</button><button onClick={() => updateStatus("applied")} className="mt-2 w-full rounded-xl border border-indigo-200 bg-indigo-50 px-4 py-2.5 text-sm font-semibold text-indigo-700 transition hover:bg-indigo-100">Mark as applied</button>{message && <p className="mt-3 text-center text-xs text-slate-500">{message}</p>}</aside></div></div></main>;
}
