"use client";
import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { OpportunityCard } from "@/components/OpportunityCard";
import { AppNav } from "@/components/AppNav";
import { CATEGORIES, OpportunityView } from "@/lib/types";
import { getOpportunities, setOpportunityStatus } from "@/lib/mock-data";

export default function DashboardPage() {
  const searchParams = useSearchParams(); const [matches, setMatches] = useState<OpportunityView[]>([]); const [category, setCategory] = useState(""); const [savedOnly, setSavedOnly] = useState(searchParams.get("saved") === "1"); const [notice, setNotice] = useState("");
  const refresh = () => setMatches(getOpportunities()); useEffect(refresh, []);
  const onSave = (id: string, status: string) => { setOpportunityStatus(id, status); refresh(); };
  const filtered = matches.filter((match) => (!category || match.category === category) && (!savedOnly || !!match.savedStatus)); const savedCount = matches.filter((match) => match.savedStatus === "saved").length; const deadlineCount = matches.filter((match) => match.deadlineTs && match.deadlineTs - Date.now() < 7 * 86400000 && match.deadlineTs > Date.now()).length;
  return <main className="min-h-screen"><AppNav /><div className="mx-auto max-w-6xl px-5 py-9 sm:px-6"><section className="rounded-3xl bg-slate-950 px-6 py-8 text-white sm:px-8"><p className="eyebrow text-indigo-300">Personal opportunity feed</p><div className="mt-3 flex flex-wrap items-end justify-between gap-5"><div><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Your Radar is on.</h1><p className="mt-2 text-slate-300">A focused shortlist based on your interests.</p></div><button onClick={() => { refresh(); setNotice("Your demo Radar is refreshed."); }} className="button-primary bg-white text-indigo-700 hover:bg-indigo-50">Refresh matches</button></div><div className="mt-7 grid grid-cols-3 divide-x divide-white/10"><div><p className="text-2xl font-bold">{matches.length}</p><p className="mt-1 text-xs text-slate-400">relevant matches</p></div><div className="pl-5"><p className="text-2xl font-bold">{savedCount}</p><p className="mt-1 text-xs text-slate-400">saved for later</p></div><div className="pl-5"><p className="text-2xl font-bold">{deadlineCount}</p><p className="mt-1 text-xs text-slate-400">deadlines this week</p></div></div></section><section className="surface mt-6 p-4"><div className="flex flex-wrap items-center gap-3"><select value={category} onChange={(e) => setCategory(e.target.value)} className="field mt-0 min-w-[200px] flex-1"><option value="">All opportunities</option>{CATEGORIES.map((item) => <option key={item} value={item} className="capitalize">{item}</option>)}</select><button onClick={() => setSavedOnly(!savedOnly)} className={`rounded-xl border px-4 py-2.5 text-sm font-semibold transition ${savedOnly ? "border-indigo-200 bg-indigo-50 text-indigo-700" : "border-slate-200 text-slate-600 hover:bg-slate-50"}`}>{savedOnly ? "Showing saved" : "Saved only"}</button><button onClick={() => setNotice("Email alerts will be connected when the backend is integrated.")} className="button-secondary">Email digest</button></div></section>{notice && <p className="mt-3 text-sm text-slate-500">{notice}</p>}<section className="mt-7"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold">{savedOnly ? "Saved opportunities" : "Best matches"}</h2><p className="text-sm text-slate-500">{filtered.length} results</p></div>{filtered.length === 0 ? <div className="surface p-10 text-center"><p className="text-lg font-bold">Nothing here yet</p><p className="mt-2 text-sm text-slate-500">Try changing the filters or save opportunities from your Radar.</p></div> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((match) => <OpportunityCard key={match.id} opp={match} onSave={onSave} />)}</div>}</section></div></main>;
}
